language: node_js
node_js:
- '0.11'
script:
- echo 11
- echo $FLOW
addons:
  artifacts:
    artifacts: true
    paths:
    - $(git ls-files -o | tr "\n" ":")
    - $(ls /var/log/*.log | tr "\n" ":")
    - $HOME/some/other/thing.log