language: node_js
node_js:
- '0.11'
- '0.10'
env:
  - ARTIFACTS_KEY=AKIAOCMZ67QT4IJBQUMQ
  - ARTIFACTS_SECRET=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
  - ARTIFACTS_BUCKET=flow-file
  global:
  - secure: mGRh7WIK/euML+kS7Nv/Maq6pf6MGNlTNve2MzfRWPy4gawYmESg3APg4EAq3Jx8fxC6nOHHprL9GG+OnWi3KjxSDVAyrF1nTB0HRRGcGRYSYE0RT/2yPW/h8z+oOxFpicvVxM5lm6qZ7NFzyJ/a+KywGOr9wWM0laJNI2t6AUorCKWPzx/yiLncpFTybaRMnzIqFU9AOR6ecJO2gwJMHaPs1cYvMxMEJvsehJ4j9KJryDPBvgoGfj65jF91kRXXx24BeDXCspegDf0ll60Jufam8xTyV4gRYifuDfjS7Tq03hx8AQdX8buyHKX8FTtvhiVqSHS0plGGPJknwQs6OTyNl9Fh4qtF42E/+7ktGZN2vS/tPY8PrT+AyItryC9hHGusmure9IIrf0zQ6XeZc/oFpKI8KHlAHaOioiXyQXy7CtX47gojVskRsM40PElToy+MqVIhQZJxU0ZXspAkqw0Z2/LGCGAr84yOaqv8ay5NPSo07jqRn0eAOUu/WDeywy32PZBRo2vnHlszBcQHA8P4LDv6xuth6KlCbJbEJmrv0fIbz6K04KSzfzGiIYE73sA7CiR3eDq9mb+GvfTTUy0wMWN8vkBju1X9W3YGVbq+QQdg/wK+SC8azmBSgJSSTfnhN3CyXPCrjUj0YoGmfupWq1Y2jAx0BYQovyMsU7Y=
  - secure: N1WCjQOCIfKAi+gXkaeITkHRDf6XF3/T6H7MHQgxdJVsXVmI360N3Obttb1e7K2fQ4f7oAknmkiV5FzQtEm0sBIlwdh/HCnNKjnHoy0ksGHxJavHW9bWqCRvDGwLqy6n68cm7GVnbOxviqIegUq8J3ZyIfu/G0EKTRCTe5w/JPhSAR+H7CojxIleSv1VHMUfss1axUin7Exa+a49PgrFBJf+Mv30xsdfaZlpgQH9butxsihWYIn8oF3VYdFK9QW+38vcVnqQYPZbFrNfpJFfNs3rhOkDNYkSU1zv15MNolPenP7vZYcQ0mJiQ4ytHt3NEFxWVO+gOu3Qfd+qxU1eS3KGcMzPyRZ76dIcF7CrKD6n+6VC8pdPKNO+H93J4nsDxErBaZJ2RQHZtnavv6+97XB8KbiplNcZGyEKhe1qnr/wFTa4LTFnLHx9XEbEJ9WuEAGu9LeakxiODvDoPTR55zK/9fzUVxkBMZNTvf4zPsj8hojxiZ7Qf0dp8E8XHk7MZR4o41dUucqTEuYme/YnpoZGw2i+DOgdXvHiqiRLRWROUxL8RwFN4Zhjif6ODBlTs6pWSLjaW66BbrSD53TF2FWwG7GZQ4uSXFYnM5BOyZdIFpTIwoD8D1o6ou5tFfGnercG73bso5Uzkpo5rCPMuj5CZyw3o4bOEkEXZcXxWE0=
  - secure: BX2DRIMZaIyABuFNGJC7agjFUcm6vfXWBvdeKMtWQqdTaR9bU6cxfq9C7dstNQJG4vv8TS1YxHTy197oszXjZBKzuDytp0+b8GFcgz51bZngzRzSMQCYRu0HEqi4oPPf7LgxXVEm2hMbJP+8lsZ0PweS/eC1Q3duDDJpFkzl2wcDagSbqPOzorXOyTf/SVwn6cz0QYF8tQNaUhL9bCs2aiwInYjxjg1cU3C+xk4DtqKyT7DJa80woBa2rRzEZx/9whmCNzYkTJ6k/qfAHaeNOJuvhTNfLoGcPusuFZlWKVdlF09u54XsTNMD/p5aVKkGF2atI4jp+I/XAalJHaSj1i93bYVqDaIau1dhFGwV1Tsj5YltGPtYWlxfgqkrOno83WM5xlft4cDRxjPwXKDiDrS5hkCH+Qq93GvMyEtODZX3ZdJYYKm8CHn9+nOHkfsWl8nnHskl6fDkCJp7mnzUoYZRw1Swe/tFelNT+ClVfRnNSSJ7//QueaMSjFroYhctLRpBHRT/ao2io5I7BCWEv8+bjX9xAb3pH1UgpBI4yWYSOeON3ynvm9HfCb2IDHG/7/lueyOHEV8g7VJcx25g14ElCujliTblJKluhE/ORlr0Ah7NCNt04TIAPmOvzRDWl3P+aW31GRBn0qZEMjUybMCET/O1B62I/v0UkmozU/A=
script:
- echo $FLOW
addons:
  artifacts:
    artifacts: true
    paths:
    - $(git ls-files -o | tr "\n" ":")
    - $(ls /var/log/*.log | tr "\n" ":")
    - $HOME/some/other/thing.log